name: Package Application with Pyinstaller

on: 
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: install req
        run: pip install -r requirements.txt ; python -m unidic download ;
        
      - name: dl upx
        run: python .github\getLatestUPX.py; 7z x upx.zip; mv upx-* upx;
      
      - name: pack:full
        run: pyinstaller --upx-dir upx TransAssistant_full.spec -y ; mv dist/TransAssistant_full ./ ; 7z a -t7z TransAssistant_full.7z TransAssistant_full
        
      - name: pack:core
        run: pyinstaller --upx-dir upx TransAssistant_core.spec -y ; mv dist/TransAssistant_core ./ ; 7z a -t7z TransAssistant_core.7z TransAssistant_core

      - name: pack:core-lite
        run: pyinstaller --upx-dir upx TransAssistant_core-lite.spec -y ; mv dist/TransAssistant_core-lite ./ ; 7z a -t7z TransAssistant_core-lite.7z TransAssistant_core-lite

      - name: pack:small
        run: pyinstaller --upx-dir upx TransAssistant_small.spec -y ; mv dist/TransAssistant_small ./ ; 7z a -t7z TransAssistant_small.7z TransAssistant_small
        
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: GUI
          path: TransAssistant_*.7z
          
      - name: release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "TransAssistant_*.7z"
          draft: false

